### ISSUE TITLE
Label Mapping

### ISSUE THREAD

**Issue by sparsick** [support-and-care/jira-to-gh-issues#3]
- [x] Mapping from issue type to labels
- [x] Handling existing vs. non-existing labels
- [x] add more context information for better mapping
- [x] Mapping priority to labels (see https://github.com/apache/maven-gh-actions-shared/pull/129)

**Comment by slawekjaranowski** [comment]
labels should be also documented like in https://github.com/apache/maven-site/pull/588

**Comment by sparsick** [comment]
Labels type (found in the above linked PR) :

-   bug
-   dependencies
-   documentation
-   enhancement

**Comment by slawekjaranowski** [comment]
It is a proposition of label list if we need we can add more

**Comment by sparsick** [comment]
Found Jira Types in Maven Clean Plugin Jira Project:
- Bug
- Improvement
- New Feature
- Task
- Dependency Upgrade

**Comment by sparsick** [comment]
Some notes about found Jira Types in Maven Clean Plugin Jira Project:

**Task** contains Dependencies Updates, refactoring

**Improvements** contains Dependencies Updates, refactoring

**Comment by slawekjaranowski** [comment]
> Some notes about found Jira Types in Maven Clean Plugin Jira Project:
> 
> **Task** contains Dependencies Updates, refactoring
> 
> **Improvements** contains Dependencies Updates, refactoring

simply it can be wrong used ... 😄

**Comment by slawekjaranowski** [comment]
```java
fieldValueHandler.addMapping(FieldValueLabelHandler.FieldType.ISSUE_TYPE, "Task", "dependencies");
```

I would like map `Task` to `maintenance`, for `dependencies` we have dedicated one.

**Comment by sparsick** [comment]
> > Some notes about found Jira Types in Maven Clean Plugin Jira Project:
> > **Task** contains Dependencies Updates, refactoring
> > **Improvements** contains Dependencies Updates, refactoring
> 
> simply it can be wrong used ... 😄

:) yes.

Nevertheless, that is the reality.
 I will research if it is possible to add more context information for the mapping. Fallback is to clean up it if it is important that is mapped correctly.

**Comment by sparsick** [comment]
> > > Some notes about found Jira Types in Maven Clean Plugin Jira Project:
> > > **Task** contains Dependencies Updates, refactoring
> > > **Improvements** contains Dependencies Updates, refactoring
> > 
> > 
> > simply it can be wrong used ... 😄
> 
> :) yes.
> 
> Nevertheless, that is the reality. I will research if it is possible to add more context information for the mapping. Fallback is to clean up it if it is important that is mapped correctly.

Implementing an `IssueProcessor` can help to add more context information to mapping to the correct label.

**Comment by slawekjaranowski** [comment]
Do we need a prefix `type` like `type:dependencies`, why not simply `dependencies`

**Comment by sparsick** [comment]
Good catch. It is a prefix of the migration tool. I will fix it.

**Comment by sparsick** [comment]
Note for myself> How to handle with already existing labels, when migration client tries to create labels

**Comment by slawekjaranowski** [comment]
> Note for myself> How to handle with already existing labels, when migration client tries to create labels

I would like to not change existing labels

**Comment by sparsick** [comment]
Now, only lables are created, that not exists

**Comment by sparsick** [comment]
> * [ ]  Mapping from issue type to labels
> 
>     * [ ]  Handling existing vs. non-existing labels
> 
>     * [ ]  add more context information for better mapping

@slawekjaranowski do you see more issues in this topic? For example, mapping Jira status to labels?

**Comment by slawekjaranowski** [comment]
We have label definition in one place: https://github.com/apache/maven-gh-actions-shared/blob/main/.github/labels.js
If we need an another label we can add to this file and label will be synchronized to all Maven repos.

**Comment by slachiewicz** [comment]
@slawekjaranowski can we open issues reporting for gh-shared-action?
